name: Deploy via SSH
'on':
  - push
  - repository_dispatch
permissions:
  actions: read
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Make sure the @v0.9.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}


      - name: Deploy to server
        run: |
          ssh-keyscan -H heshamelhamdani.com >> ~/.ssh/known_hosts 
          scp -r * helhamdani@heshamelhamdani.com:/var/www/heshamelhamdani.com/html